# Docker Compose for using pre-built image from Docker Hub
services:
  web:
    # Replace with your Docker Hub image name
    image: yourusername/pyggy-expense-tracker:latest
    ports:
      - "8000:8000"
    volumes:
      # Persist database
      - ./db.sqlite3:/app/db.sqlite3
      # Optional: Override settings for local development
      - ./expense_tracker/settings.py:/app/expense_tracker/settings.py:ro
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-change-me-in-production}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-False}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-*}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped