# Generated by Django 5.2.1 on 2025-05-31 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.payee'),
        ),
    ]
