# Generated by Django 5.2.1 on 2025-05-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_change_payment_date_to_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
