# Generated by Django 5.2.1 on 2025-05-31 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_expenseitem_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="payee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="expenses.payee",
            ),
        ),
    ]
