# Generated by Django 5.2.1 on 2025-06-01 12:07

from django.db import migrations, models


def create_default_settings(apps, schema_editor):
    """Create default settings instance."""
    Settings = apps.get_model("expenses", "Settings")
    Settings.objects.get_or_create(
        pk=1, defaults={"currency": "USD", "locale": "en_US"}
    )


def delete_default_settings(apps, schema_editor):
    """Delete default settings instance."""
    Settings = apps.get_model("expenses", "Settings")
    Settings.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0006_make_payee_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", help_text="ISO 4217 currency code", max_length=3
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        default="en_US",
                        help_text="Locale identifier (e.g., en_US, fr_FR)",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Settings",
                "verbose_name_plural": "Settings",
            },
        ),
        migrations.RunPython(create_default_settings, delete_default_settings),
    ]
