# Generated by Django 5.2.1 on 2025-06-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_expense_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('endless_recurring', 'Endless Recurring'), ('split_payment', 'Split Payment'), ('one_time', 'One Time'), ('recurring_with_end', 'Recurring with End Date')], max_length=20),
        ),
    ]
