# Generated by Django 5.2.1 on 2025-06-02 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0011_populate_default_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="month",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="expenses.budget"
            ),
        ),
    ]
