# Generated by Django 5.2.1 on 2025-06-02 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_make_budget_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.budget'),
        ),
    ]
