# Generated by Django 5.2.1 on 2025-06-04 01:08

from django.db import migrations, models


def populate_due_dates(apps, schema_editor):
    """Populate due_date with started_at values for existing expenses"""
    Expense = apps.get_model("expenses", "Expense")
    for expense in Expense.objects.all():
        expense.due_date = expense.started_at
        expense.save()


def reverse_populate_due_dates(apps, schema_editor):
    """Reverse migration - nothing to do since we're removing the field"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0016_expense_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="due_date",
            field=models.DateField(help_text="Due date for expense", null=True),
        ),
        migrations.RunPython(populate_due_dates, reverse_populate_due_dates),
        migrations.AlterField(
            model_name="expense",
            name="due_date",
            field=models.DateField(help_text="Due date for expense"),
        ),
    ]
