# Generated by Django 5.2.1 on 2025-06-04 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_auto_20250604_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='due_date',
        ),
    ]
