# Generated by Django 5.2.1 on 2025-06-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0022_migrate_expenseitem_payments_to_payment_records"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expenseitem",
            name="status",
        ),
    ]
