# Generated by Django 5.2.1 on 2025-06-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0023_remove_expenseitem_status_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expenseitem",
            name="payment_date",
        ),
        migrations.RemoveField(
            model_name="expenseitem",
            name="payment_id",
        ),
        migrations.RemoveField(
            model_name="expenseitem",
            name="payment_method",
        ),
    ]
