# Generated by Django 5.2.1 on 2025-06-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0024_remove_old_payment_fields_from_expenseitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="payment_id",
        ),
        migrations.AddField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Optional transaction reference (e.g., bank transfer ID, check number, receipt number)",
                max_length=255,
                null=True,
            ),
        ),
    ]
