# Generated by Django 5.2.1 on 2025-06-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0025_rename_payment_id_to_transaction_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Month",
            new_name="BudgetMonth",
        ),
    ]
