# Generated by Django 5.2.1 on 2025-06-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0026_rename_month_to_budget_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="currency",
            field=models.CharField(
                choices=[("PLN", "PLN"), ("EUR", "EUR"), ("USD", "USD")],
                default="PLN",
                max_length=3,
            ),
        ),
    ]
