####################################################################
#
####################################################################

name: "Code lint"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev ]

jobs:
  unittests:
    name: "Linting"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # os: [ ubuntu-latest, macos-latest, windows-latest ]
        os: [ ubuntu-latest ]
        # Need to quote "3.10" or it will end up being "3.1" at runtime if given as float
        python: [ "3.12" ]

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: "Checkout sources"
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/paths-changes-filter
      - name: "Look for changed files..."
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            srcs:
              - '**/*.py'

      - name: "Setup Python"
        if: steps.filter.outputs.srcs == 'true'
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python }}

      # https://github.com/marketplace/actions/wemake-python-styleguide
      # https://wemake-python-stylegui.de/en/latest/pages/usage/integrations/github-actions.html
      - name: "Running linter..."
        if: steps.filter.outputs.srcs == 'true'
        uses: wemake-services/wemake-python-styleguide@1.1.0

      - name: "Running mypy..."
        if: steps.filter.outputs.srcs == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          mypy expenses/ --show-error-codes
