####################################################################
#
####################################################################

name: "MD Lint"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev ]

jobs:
  markdown_lint:
    name: "Markdown linter"
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: "Checkout sources"
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/paths-changes-filter
      - name: "Look for changed doc related files..."
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs:
              - 'README.md'
              - 'docs/*.md'
              - 'project/*.md'

      # https://github.com/marketplace/actions/my-markdown-linter
      - name: "Running markdown linter..."
        uses: ruzickap/action-my-markdown-linter@v1
        if: steps.filter.outputs.docs == 'true'
        with:
          exclude: |
            # LICENSE is externally sourced and we're not going to fix it.
            "LICENSE.md"
          config_file: .markdownlint.yaml.dist
